spring:
  application:
    name: ray-little
  datasource:
    url: jdbc:postgresql://localhost:5432/little_ray_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  api:
    prefix: api/v1

jwt:
  expiration: 3600
  secretKey: "YXBpX2tleSA9IHJjYS5waWJzYW9yY2lidTIzNGxidTQz"


